### ISSUE TITLE
Fixevi

### ISSUE THREAD

**Issue by codeAdrian** [pgalina98/ReactCourse#1]
Super si odradio, super što si dodao ove spinnere i što si koristio objekte za state. Imam samo par komentara

U App komponenti imaš naming conflict - data koji ti dolazi iz statea ti je u konfliktu sa data iz fetcha. Renameaj data iz fetcha u nesto drugo ili odmah destrukturiraj kao `({releases, pagination}) =>` inace ti se VSCode se buni da treba `data` biti u hook-u što nije slučaj ovdje.

```
const App = () => {
  const [data, setData] = useState({ fetching: false, releases: [] });
  const [pagination, setPagination] = useState({ currentPage: 1, pages: 1 });

  useEffect(() => {
    const getRecordsData = async () => {
      setData({ ...data, fetching: true });

      await fetch(
        `https://api.discogs.com/users/adrianmusiccollector/collection/folders/0/releases?page=${pagination.currentPage.toString()}`
      )
        .then((response) => response.json())
        .then((data) => {
          console.log("DATA: ", data);
          setData({ fetching: false, releases: data.releases });
          setPagination({ ...pagination, pages: data.pagination.pages });
        })
        .catch((error) => console.log("ERROR: ", error));
    };

    getRecordsData();
  }, [pagination.currentPage]);
```

Preporuka za bolji naming booleana je da koristiš upitne izraze tipa `isFetching` umjesto `fetching`. To je neki best practice u industriji i po tome možeš razlikovati booleane i ostale tipove po imenu. Također ti onda `isFetching ? something() : somethingElse()` izgleda bolje kad čitaš.

Za CollectionTable, kako bi izbjegao nestanje velikih chunkova koda u ternaryju u return statementu, mozes refaktorirati

```
  return (
    <div className="collectionTable">
      {children.fetching ? (
        <>
          <CircularProgress style={{ marginRight: "15px" }} />
          <span>Loading...</span>
        </>
      ) : (
        <table className="collectionTableDataTable">
          <thead>
            <tr>
```

u

```
if(children.fetching) {
  return (
    <div className="collectionTable">
          <CircularProgress style={{ marginRight: "15px" }} />
          <span>Loading...</span>
    </div>
  )

return (
    <div className="collectionTable">
        <table className="collectionTableDataTable">
        </table>
    </div>
  )
}
```

Imat ćeš mnogo čitljiviji kod i manje nestanih chunkova u return-u.

Umjesto togglanja klase, mozes koristiti ovakav selektor `paginationButton:disabled` pošto ti je u HTML-u već setan. Ako baš želiš togglati klasu, napravi `const isDisabled =  pagination.currentPage === 1;` i onda reusaj da nemas dupliciran kod.

```
        className={
          pagination.currentPage === 1
            ? "paginationButton paginationButtonDisabled"
            : "paginationButton"
        }
```

Ovo ti je redundantno

```
pagination.currentPage === pagination.pages ? true : false
```

mozes pisati samo `disabled={pagination.currentPage === pagination.pages}` jer ovakav check uvijek vrati Boolean

Ako ti funkcija ne prima argumente ili su jednaki onom što se predaje ne moraš pisati

```
        onClick={() => {
          onPageUp();
        }}
```

ovdje imaš () u anonymous () => funkciji i u funkciji koju pozivaš pa može prop biti `onClick={onPageUp}`

```
await fetch
```

Ne moraš `await` stavljati na fetch ako imaš `then`. da nismo koristili then, onda bi morao sve awaitat.

Ovo sljedeće možeš skratiti na `.map(({name}) => name)`

```
          .map((artist) => {
            return artist.name;
          })
```
Za SearchForm i TableItem primjeni ove prethodne savjete. Mislim da tu i tamo možeš nešto bolje napisati.

Sve u svemu, ovo su čisto stilski savjeti i best practice savjeti. Super odrađeno, kad završiš javi pa ti pregledam još jednom

**Comment by pgalina98** [comment]
Hvala na povratnoj informaciji :)
Sve preporuke su primijenjene i pushane na repozitorij.
